### ISSUE TITLE
Installation via Homebrew on OS X

### ISSUE THREAD

**Issue by ararslan** [lnishan/vector#2]
Hello!

I just wanted to let you know that I think this project is really neat, so I've added it to my [Homebrew](https://brew.sh) tap: https://github.com/ararslan/homebrew-pints. This means that OS X users can install `vector` using `brew install ararslan/pints/lni-vector`.

Since the word "vector" is pretty common I was worried about naming conflicts, so it installs into `/usr/local/include/lni` rather than `/usr/local/include`, which means that it has to be used as `#include "lni/vector.hpp"`. Does that seem like a reasonable thing to do or would you recommend a different approach?

Thanks and keep up the good work! 😄

**Comment by lnishan** [comment]
Hello, @ararslan :)

Thanks for the homebrew tap you made. Highly appreciated :)

Yep, I think that looks decent to me.
I've actually been thinking about implementing other (supercharged) STLs,
so having a "lni-" prefix would be pretty nice. (I might also change the name of this repo.)
As for the include directory, that looks good to me as well :)

Thanks for the issue and great suggestions!

**Comment by ararslan** [comment]
Okay great, I'll make sure to update the Homebrew formula should the name here change and I'll keep the `lni` prefix. Thanks!
