### ISSUE TITLE
There is a bug in one of the constructor 

### ISSUE THREAD

**Issue by pritpal20** [lnishan/vector#3]
vector<T>::vector(InputIt first, InputIt last) {
		std::cout << "Inside ... \n" ;
		size_type i, count = last - first;
		std::cout <<"count ="  << count << std::endl;
		rsrv_sz = count << 2;
// the size is not updated 
		vec_sz = count;
		arr = new T[rsrv_sz];
		for (i = 0; i < count; ++i, ++first)
			arr[i] = *first;
	}

**Comment by lnishan** [comment]
@pritpal20 
Thanks for tracking down and reporting the issue :)

Fixed in: https://github.com/lnishan/vector/commit/0e42ec1b61f6b1dd04f23a90eb7a013c8038c0e6
