### ISSUE TITLE
compile error when creating object of type lni::vector v(5,0)

### ISSUE THREAD

**Issue by pritpal20** [lnishan/vector#4]
compilation error when creating object of type 
vector<T>::vector(typename vector<T>::size_type n, const T &value) 

vector.hpp: In instantiation of ‘lni::vector<T>::vector(InputIt, InputIt) [with InputIt = int; T = int]’:
mytester.cpp:43:33:   required from here
vector.hpp:153:13: error: invalid type argument of unary ‘*’ (have ‘int’)
    arr[i] = *first;

There is a conflict between two constructor

**Comment by lnishan** [comment]
I'll look into these issues when I have time (~ 3 days).
Thanks for reporting!

**Comment by lnishan** [comment]
I think where the issues are.
I'll attempt at a fix later.

My apologies.
I've been quite ill. I should be able to fix the 2 issues you reported by mid Jan.

**Comment by lnishan** [comment]
Fixed! :)
Turns out that I didn't know how to initialize templated iterators correctly.

Thanks for reporting :)
